resolver: lts-4.2
packages:
- '.'
flags:
   idris:
     FFI: true
     GMP: True
extra-deps: 
- annotated-wl-pprint-0.7.0
- cheapskate-0.1.0.4
- libffi-0.1
nix:
   enable: false
   shell-file: stack-shell.nix
